# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: profe_farmacia_dario
  pool: 5
  username: postgres
  password: 3833105m
  host: localhost

